server:
  port: 8090
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
